// Mapa autoritativo: ID do perk (chave usada em Perks.* no jogo) → nome PT-BR exibido no site.
// O mod v1.7+ exporta IDs em inglês; o decoder usa este mapa para traduzir antes de salvar.
// Entradas antigas (nomes em PT-BR) passam direto — não são chaves deste mapa.
export const SKILL_NAMES: Record<string, string> = {
  Sprinting:    'Corrida',
  Lightfooted:  'Pés Leves',
  Nimble:       'Agilidade',
  Sneaking:     'Furtividade',
  Fitness:      'Condicionamento',
  Strength:     'Força',
  Axe:          'Machado',
  LongBlunt:    'Contundente Longo',
  ShortBlunt:   'Contundente Curto',
  LongBlade:    'Lâmina Longa',
  ShortBlade:   'Lâmina Curta',
  Spear:        'Lança',
  Maintenance:  'Manutenção',
  Aiming:       'Mira',
  Reloading:    'Recarga',
  Cooking:      'Culinária',
  Fishing:      'Pesca',
  Trapping:     'Armadilhas',
  Foraging:     'Coleta',
  FirstAid:     'Primeiros Socorros',
  Carpentry:    'Carpintaria',
  Agriculture:  'Agricultura',
  Electrical:   'Eletricidade',
  Mechanics:    'Mecânica',
  MetalWelding: 'Soldagem',
  Tailoring:    'Costura',
  Knapping:     'Lascamento',
  Carving:      'Entalhamento',
  Masonry:      'Alvenaria',
  Pottery:      'Cerâmica',
  Blacksmith:   'Ferraria',
  Glassmaking:  'Vidraria',
  AnimalCare:   'Cuidado Animal',
  Butchering:   'Abate',
  Tracking:     'Rastreamento',
};
