-- migration v24: PZRX6 — 12 novas colunas de estatísticas estendidas
ALTER TABLE entries ADD COLUMN IF NOT EXISTS eggs_collected    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS milk_produced     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS stone_structures  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS ceramic_items     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS forged_weapons    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS km_driven         INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS cities_visited    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS military_visited  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS meals_cooked      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS water_collected   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS materials_crafted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS animal_tracks     INTEGER NOT NULL DEFAULT 0;
