-- migration v27: PZRX8 — 9 colunas de estatísticas estendidas
ALTER TABLE entries ADD COLUMN IF NOT EXISTS furniture_crafted  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS clothes_crafted    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS cheese_produced    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS doors_opened       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS sleep_locations    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS basements_explored INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS stations_used      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS animal_species     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS days_no_canned     INTEGER NOT NULL DEFAULT 0;
