// GERADO a partir dos arquivos do jogo (B42): media/scripts (ItemType = base:weapon)
// + nomes pt-BR de media/lua/shared/Translate/PTBR/ItemName.json. Não editar à mão.
export const WEAPON_NAMES: Record<string, string> = {
  "Base.AnimalBone": "Osso de Animal",
  "Base.AssaultRifle": "Rifle de Assalto M16",
  "Base.AssaultRifle2": "Rifle M1A",
  "Base.Axe": "Machado de Bombeiro",
  "Base.AxeStone": "Machado Rústico de Pedra",
  "Base.Axe_Old": "Machado",
  "Base.Axe_Sawblade": "Machado com Lâmina de Serra",
  "Base.Axe_Sawblade_Hatchet": "Machadinha com Lâmina de Serra",
  "Base.Axe_ScrapCleaver": "Cutelo-Machado de Sucata Metálica",
  "Base.BadmintonRacket": "Raquete de Badminton",
  "Base.BallPeenHammer": "Martelo de Bola",
  "Base.BallPeenHammerForged": "Martelo de Bola",
  "Base.Banjo": "Banjo",
  "Base.BanjoNeck_Broken": "Braço de Banjo Quebrado",
  "Base.BarBell": "Barra de Pesos",
  "Base.BarBell_Forged": "Barra de Pesos",
  "Base.BareHands": "Mãos Nuas",
  "Base.BaseballBat": "Taco de Beisebol",
  "Base.BaseballBat_Broken": "Taco de Beisebol Quebrado",
  "Base.BaseballBat_Broken_Nails": "Taco de Beisebol Quebrado com Pregos",
  "Base.BaseballBat_Can": "Taco de Beisebol - Reforçado com Lata",
  "Base.BaseballBat_Crafted": "Taco de Beisebol Artesanal",
  "Base.BaseballBat_GardenForkHead": "Taco de Beisebol com Cabeça de Forcado de Jardim",
  "Base.BaseballBat_Metal": "Taco de Beisebol de Metal",
  "Base.BaseballBat_Metal_Bolts": "Taco de Beisebol de Metal com Parafusos",
  "Base.BaseballBat_Metal_Sawblade": "Taco de Beisebol de Metal com Lâmina de Serra",
  "Base.BaseballBat_Nails": "Taco de Beisebol com Pregos",
  "Base.BaseballBat_RailSpike": "Taco de Beisebol com Cravo Ferroviário",
  "Base.BaseballBat_RakeHead": "Taco de Beisebol com Pontas de Ancinho",
  "Base.BaseballBat_Sawblade": "Taco de Beisebol com Lâmina de Serra",
  "Base.BaseballBat_ScrapSheet": "Taco de Beisebol - Reforçado com Chapa de Metal",
  "Base.BaseballBat_Spiked": "Taco de Beisebol com Pontas",
  "Base.BlockMace": "Maça de Bloco de Ferro",
  "Base.BlockMaul": "Marreta de Bloco de Ferro",
  "Base.BluePen": "Caneta - Azul",
  "Base.BoltCutters": "Alicate Corta-vergalhão",
  "Base.BoneClub": "Clava de Osso",
  "Base.BoneClub_Spiked": "Clava de Osso com Pontas",
  "Base.BowlingPin": "Pino de Boliche",
  "Base.BowlingPin_Nails": "Pino de Boliche com Pregos",
  "Base.Branch_Broken": "Galho Quebrado",
  "Base.Branch_Broken_Nails": "Galho Quebrado com Pregos",
  "Base.BrassNameplate": "Placa de Identificação de Latão",
  "Base.BreadKnife": "Faca de Pão",
  "Base.Broom": "Vassoura",
  "Base.Broom_BarbedWire": "Vassoura com Arame Farpado",
  "Base.Broom_Twig": "Vassoura de Graveto",
  "Base.BucketMace_Metal": "Marreta de Balde - Cabo de Metal",
  "Base.BucketMace_Wood": "Marreta de Balde - Cabo de Madeira",
  "Base.ButterKnife": "Faca de Manteiga",
  "Base.ButterKnife_Gold": "Faca de Manteiga de Ouro",
  "Base.ButterKnife_Silver": "Faca de Manteiga de Prata",
  "Base.CanoePadel": "Remo de Canoa",
  "Base.CanoePadelX2": "Remo de Canoa - Duas Pás",
  "Base.CanoePadelX2_Broken": "Remo de Canoa Quebrado",
  "Base.CarpentryChisel": "Formão de Carpinteiro",
  "Base.CarvingFork2": "Garfo de Trinchar",
  "Base.ChairLeg": "Perna de Cadeira",
  "Base.ChairLeg_Nails": "Perna de Cadeira com Pregos",
  "Base.ClosedUmbrellaBlack": "Guarda-chuva (Fechado)",
  "Base.ClosedUmbrellaBlue": "Guarda-chuva (Fechado)",
  "Base.ClosedUmbrellaRed": "Guarda-chuva (Fechado)",
  "Base.ClosedUmbrellaTINTED": "Guarda-chuva (Fechado)",
  "Base.ClosedUmbrellaWhite": "Guarda-chuva (Fechado)",
  "Base.ClubHammer": "Marreta Pequena",
  "Base.ClubHammerForged": "Marreta Pequena",
  "Base.CompassGeometry": "Compasso Geométrico",
  "Base.CraftedFishingRod": "Vara de Pesca Improvisada",
  "Base.Crowbar": "Pé de Cabra",
  "Base.CrowbarForged": "Pé de Cabra",
  "Base.CrudeKnife": "Faca Simples de Metal",
  "Base.CrudeShortSword": "Espada Curta Simples",
  "Base.CrudeSword": "Espada Simples",
  "Base.CrudeSword_Broken": "Espada Simples Quebrada",
  "Base.Cudgel_Bone": "Porrete com Pontas de Osso",
  "Base.Cudgel_Brake": "Porrete com Disco de Freio",
  "Base.Cudgel_GardenForkHead": "Porrete com Cabeça de Forcado de Jardim",
  "Base.Cudgel_Nails": "Porrete com Pregos",
  "Base.Cudgel_Railspike": "Porrete com Cravos Ferroviários",
  "Base.Cudgel_Sawblade": "Porrete com Lâmina de Serra",
  "Base.Cudgel_ScrapSheet": "Porrete - Reforçado com Chapa Metálica",
  "Base.Cudgel_SpadeHead": "Porrete com Cabeça de Pá de Corte",
  "Base.Cudgel_Spike": "Porrete com Pontas",
  "Base.DoubleBarrelShotgun": "Espingarda de Cano Duplo",
  "Base.DoubleBarrelShotgunSawnoff": "Espingarda de Cano Duplo Serrada",
  "Base.Drumstick": "Baqueta",
  "Base.DullBoneKnife": "Faca de Osso Cega",
  "Base.DumbBell": "Haltere",
  "Base.DumbBell_Forged": "Haltere",
  "Base.EngineMaul": "Marreta de Peças de Motor",
  "Base.EntrenchingTool": "Pá de Entrincheiramento",
  "Base.FISH_DEV_ITEM": "ITEM DE DESENVOLVIMENTO DE PESCA (NÃO GERAR)",
  "Base.FieldHockeyStick": "Taco de Hóquei de Campo",
  "Base.FieldHockeyStick_Broken": "Taco de Hóquei de Campo Quebrado",
  "Base.FieldHockeyStick_Broken_Nails": "Taco de Hóquei de Campo Quebrado com Pregos",
  "Base.FieldHockeyStick_Nails": "Taco de Hóquei de Campo com Pregos",
  "Base.FieldHockeyStick_Sawblade": "Taco de Hóquei de Campo com Lâmina de Serra",
  "Base.FightingKnife": "Faca de Combate",
  "Base.File": "Lima",
  "Base.FireplacePoker": "Atiçador de Lareira",
  "Base.Firewood": "Lenha",
  "Base.Firewood_Nails": "Lenha com Pregos",
  "Base.FishingRod": "Vara de Pesca",
  "Base.FishingRodBreak": "Vara de Pesca sem Linha",
  "Base.FlintKnife": "Faca de Pedra",
  "Base.FlintNodule": "Nódulo de Sílex",
  "Base.Flute": "Flauta",
  "Base.Fork": "Garfo",
  "Base.ForkForged": "Garfo Forjado",
  "Base.Fork_Bone": "Garfo de Osso",
  "Base.Fork_Gold": "Garfo de Ouro",
  "Base.Fork_Silver": "Garfo de Prata",
  "Base.Gaffhook": "Bicheiro",
  "Base.GardenFork": "Forcado de Jardim",
  "Base.GardenForkHead": "Cabeça de Forcado de Jardim",
  "Base.GardenForkHead_Forged": "Cabeça de Forcado de Jardim",
  "Base.GardenFork_Forged": "Forcado de Jardim",
  "Base.GardenHoe": "Enxada de Jardim",
  "Base.GardenHoeForged": "Enxada de Jardim",
  "Base.GardenToolHandle_Broken": "Cabo Quebrado de Ferramenta de Jardinagem",
  "Base.Gavel": "Malhete",
  "Base.GlassShiv": "Punhal de Vidro",
  "Base.Golfclub": "Taco de Golfe",
  "Base.GreenPen": "Caneta - Verde",
  "Base.GridlePan": "Frigideira Grill",
  "Base.GuitarAcoustic": "Violão",
  "Base.GuitarAcousticNeck_Broken": "Braço de Violão Quebrado",
  "Base.GuitarElectric": "Guitarra Elétrica",
  "Base.GuitarElectricBass": "Baixo Elétrico",
  "Base.GuitarElectricBassNeck_Broken": "Braço de Baixo Elétrico Quebrado",
  "Base.GuitarElectricNeck_Broken": "Braço de Guitarra Elétrica Quebrado",
  "Base.Hammer": "Martelo de Unha",
  "Base.HammerForged": "Martelo de Unha",
  "Base.HammerStone": "Martelo de Pedra",
  "Base.HandAxe": "Machadinha",
  "Base.HandAxeForged": "Machadinha",
  "Base.HandAxe_Old": "Machadinha Antiga",
  "Base.HandFork": "Garfo de Jardinagem",
  "Base.HandScythe": "Foice de Mão",
  "Base.HandScytheForged": "Foice de Mão",
  "Base.HandShovel": "Pá de Jardinagem",
  "Base.HandguardDagger": "Adaga com Guarda",
  "Base.Handiknife": "Handiknife",
  "Base.Handle": "Cabo Médio",
  "Base.Handle_Can": "Cabo Médio - Reforçado com Lata",
  "Base.Handle_Nails": "Cabo Médio com Pregos",
  "Base.Hatchet_Bone": "Machadinha de Guerra de Osso",
  "Base.HobbyHorse": "Cavalinho de Pau",
  "Base.HuntingKnife": "Faca de Caça",
  "Base.HuntingKnifeForged": "Faca de Caça",
  "Base.HuntingRifle": "Rifle MSR788",
  "Base.IceAxe": "Picareta de Gelo",
  "Base.IceHockeyStick": "Taco de Hóquei no Gelo",
  "Base.IceHockeyStick_BarbedWire": "Taco de Hóquei no Gelo com Arame Farpado",
  "Base.IcePick": "Picador de Gelo",
  "Base.IronBar": "Barra de Ferro",
  "Base.IronBarHalf": "Meia Barra de Ferro",
  "Base.JS14_Rifle": "Rifle JS-14",
  "Base.JS3T_Shotgun": "Escopeta Tática JS-3T",
  "Base.JawboneBovide": "Mandíbula",
  "Base.JawboneBovide_Axe": "Machado de Guerra de Mandíbula",
  "Base.JawboneBovide_Club": "Clava de Mandíbula",
  "Base.JawboneBovide_Morningstar": "Maça-estrela de Mandíbula",
  "Base.Katana": "Katana",
  "Base.Katana_Broken": "Katana Quebrada",
  "Base.KettleMace_Metal": "Marreta de Chaleira - Cabo de Metal",
  "Base.KettleMace_Wood": "Marreta de Chaleira - Cabo de Madeira",
  "Base.Keytar": "Keytar",
  "Base.KitchenKnife": "Faca de Cozinha",
  "Base.KitchenKnifeForged": "Faca de Cozinha",
  "Base.KnifeButterfly": "Canivete Borboleta",
  "Base.KnifeFillet": "Faca de Filetar",
  "Base.KnifeParing": "Faca de Descascar",
  "Base.KnifePocket": "Canivete",
  "Base.KnifeShiv": "Faca Improvisada",
  "Base.KnifeSushi": "Faca de Sushi",
  "Base.L92_Carbine": "Carabina L92",
  "Base.L94_Rifle": "Rifle L94",
  "Base.LaCrosseStick": "Taco de Lacrosse",
  "Base.LargeAnimalBone": "Osso de Animal Grande",
  "Base.LargeBoneClub": "Clava de Osso Resistente",
  "Base.LargeBoneClub_Spiked": "Clava de Osso Resistente com Espinhos",
  "Base.LargeBranch": "Galho Grande",
  "Base.LargeHook": "Gancho Grande",
  "Base.LargeKnife": "Faca Grande",
  "Base.LargeKnife_Scrap": "Faca Grande de Sucata Metálica",
  "Base.LeadPipe": "Tubo de Chumbo",
  "Base.LeafRake": "Ancinho para Folhas",
  "Base.LetterOpener": "Abridor de Cartas",
  "Base.LongCrudeKnife": "Faca Longa Simples de Metal",
  "Base.LongHandle": "Cabo Grande",
  "Base.LongHandle_Brake": "Cabo Grande com Disco de Freio",
  "Base.LongHandle_Broken": "Cabo Grande Quebrado",
  "Base.LongHandle_Broken_Nails": "Cabo Grande Quebrado com Pregos",
  "Base.LongHandle_Can": "Cabo Grande - Reforçado com Lata",
  "Base.LongHandle_Nails": "Cabo Grande com Pregos",
  "Base.LongHandle_Railspike": "Cabo Grande com Cravo Ferroviário",
  "Base.LongHandle_RakeHead": "Cabo Grande com Dentes de Ancinho",
  "Base.LongHandle_Sawblade": "Cabo Grande com Lâmina de Serra",
  "Base.LongMace": "Maça Longa",
  "Base.LongMace_Stone": "Maça Longa de Pedra",
  "Base.LongSpikedClub": "Clava Longa com Espinhos",
  "Base.LongStick": "Vara Longa",
  "Base.LongStick_Broken": "Vara Longa Quebrada",
  "Base.MSR7T_Rifle": "Rifle Tático MSR7T",
  "Base.Mace": "Maça",
  "Base.Mace_Stone": "Maça de Pedra",
  "Base.Machete": "Facão",
  "Base.MacheteForged": "Facão",
  "Base.MacheteKnife": "Faca de Lâmina de Facão",
  "Base.Machete_Crude": "Facão de Sucata Metálica",
  "Base.MasonsChisel": "Talhadeira de Pedreiro",
  "Base.MasonsTrowel": "Colher de Pedreiro",
  "Base.MeatCleaver": "Cutelo de Carne",
  "Base.MeatCleaverForged": "Cutelo de Carne",
  "Base.MeatCleaver_Scrap": "Cutelo de Sucata Metálica",
  "Base.MetalBar": "Haste de Aço",
  "Base.MetalPipe": "Tubo de Ferro",
  "Base.MetalPipe_Broken": "Tubo de Ferro Quebrado",
  "Base.MetalPipe_Railspike": "Tubo de Ferro com Cravo Ferroviário",
  "Base.MetalworkingChisel": "Talhadeira para Metal",
  "Base.MetalworkingPunch": "Punção para Metalurgia",
  "Base.Mop": "Esfregão",
  "Base.Morningstar_Scrap": "Maça-estrela de Sucata Metálica",
  "Base.Morningstar_Scrap_Short": "Maça-estrela de Sucata Metálica - Curta",
  "Base.Multitool": "Multiferramenta",
  "Base.Nightstick": "Cassetete",
  "Base.Pan": "Frigideira",
  "Base.PanForged": "Frigideira",
  "Base.Pen": "Caneta - Preta",
  "Base.PenFancy": "Caneta Tinteiro",
  "Base.PenMultiColor": "Caneta Multicolorida",
  "Base.PenSpiffo": "Caneta - Spiffo",
  "Base.Pencil": "Lápis",
  "Base.PencilSpiffo": "Lápis - Spiffo",
  "Base.PickAxe": "Picareta",
  "Base.PickAxeForged": "Picareta",
  "Base.PipeWrench": "Chave Grifo",
  "Base.Pistol": "Pistola M9",
  "Base.Pistol2": "Pistola M1911",
  "Base.Pistol3": "Pistola B-F",
  "Base.Plank": "Tábua",
  "Base.Plank_Brake": "Tábua com Disco de Freio",
  "Base.Plank_Broken": "Tábua Quebrada",
  "Base.Plank_Broken_Nails": "Tábua Quebrada com Pregos",
  "Base.Plank_Nails": "Tábua com Pregos",
  "Base.Plank_Saw": "Tábua com Serra",
  "Base.Plank_Sawblade": "Tábua com Lâmina de Serra",
  "Base.Plunger": "Desentupidor",
  "Base.Plunger_BarbedWire": "Desentupidor com Arame Farpado",
  "Base.Poolcue": "Taco de Sinuca",
  "Base.PrimitiveScythe": "Gadanha com Lâmina de Pedra",
  "Base.RailroadSpike": "Cravo Ferroviário",
  "Base.RailroadSpikeKnife": "Faca de Cravo Ferroviário",
  "Base.RailroadSpikePuller": "Extrator de Cravos Ferroviários",
  "Base.RailroadSpikePullerOld": "Extrator de Cravos Ferroviários",
  "Base.Rake": "Ancinho",
  "Base.Ratchet": "Chave de Catraca",
  "Base.RedPen": "Caneta - Vermelha",
  "Base.Revolver": "Revólver de Patrulha",
  "Base.Revolver_CapGun": "Pistola de Brinquedo com Espoleta",
  "Base.Revolver_Long": "Magnum",
  "Base.Revolver_Short": "Revólver SN38",
  "Base.Rifle_CapGun": "Rifle de Brinquedo com Espoleta",
  "Base.RollingPin": "Rolo de Massa",
  "Base.Sapling": "Muda",
  "Base.Saucepan": "Caçarola",
  "Base.SaucepanCopper": "Caçarola de Cobre",
  "Base.Saw_Flint": "Serra de Sílex",
  "Base.Saxophone": "Saxofone",
  "Base.Scalpel": "Bisturi",
  "Base.Scissors": "Tesoura",
  "Base.ScissorsForged": "Tesoura Rudimentar",
  "Base.ScrapMaul": "Marreta de Sucata Metálica",
  "Base.ScrapWeaponGardenFork": "Arma de Sucata Metálica com Forcado de Jardim",
  "Base.ScrapWeaponRakeHead": "Arma de Sucata Metálica com Cabeça de Ancinho",
  "Base.ScrapWeaponSpade": "Arma de Sucata Metálica com Cabeça de Pá de Corte",
  "Base.ScrapWeapon_Brake": "Arma de Sucata Metálica com Disco de Freio",
  "Base.Screwdriver": "Chave de Fenda",
  "Base.Screwdriver_Improvised": "Chave de Fenda Improvisada",
  "Base.Screwdriver_Old": "Chave de Fenda",
  "Base.SharpBone_Long": "Osso Longo e Afiado",
  "Base.SheetMetalSnips": "Tesoura para Chapa Metálica",
  "Base.ShortBat": "Bastão Curto",
  "Base.ShortBat_Can": "Bastão Curto - Reforçado com Lata",
  "Base.ShortBat_Nails": "Bastão Curto com Pregos",
  "Base.ShortBat_RailSpike": "Bastão Curto com Cravo Ferroviário",
  "Base.ShortBat_RakeHead": "Bastão Curto com Dentes de Ancinho",
  "Base.ShortBat_Sawblade": "Bastão Curto com Lâmina de Serra",
  "Base.ShortSword": "Espada Curta",
  "Base.ShortSword_Scrap": "Espada Curta de Sucata Metálica",
  "Base.Shotgun": "Espingarda JS-2000",
  "Base.ShotgunSawnoff": "Espingarda JS-2000 de Cano Serrado",
  "Base.Shovel": "Pá de Corte",
  "Base.Shovel2": "Pá",
  "Base.Sledgehammer": "Marreta",
  "Base.Sledgehammer2": "Marreta",
  "Base.SledgehammerForged": "Marreta",
  "Base.SmallKnife": "Faca Pequena",
  "Base.SmashedBottle": "Garrafa Quebrada",
  "Base.SmithingHammer": "Martelo de Ferreiro",
  "Base.SnowShovel": "Pá de Neve",
  "Base.SpadeForged": "Pá de Corte",
  "Base.SpadeHead": "Lâmina de Pá de Corte",
  "Base.SpadeWood": "Pá de Corte de Madeira",
  "Base.SpearCrafted": "Lança de Madeira",
  "Base.SpearCraftedFireHardened": "Lança de Madeira (Endurecida pelo Fogo)",
  "Base.SpearCrude": "Lança com Ponta Simples de Metal",
  "Base.SpearCrudeLong": "Lança com Ponta Longa e Simples de Metal",
  "Base.SpearFightingKnife": "Lança com Faca de Combate",
  "Base.SpearGlass": "Lança com Ponta de Vidro",
  "Base.SpearHandFork": "Lança com Garfo de Jardinagem",
  "Base.SpearHuntingKnife": "Lança com Faca de Caça",
  "Base.SpearKnife": "Lança com Faca de Cozinha",
  "Base.SpearKnifeSmall": "Lança com Faca Pequena",
  "Base.SpearLargeKnife": "Lança com Faca Grande",
  "Base.SpearLong": "Lança com Ponta Longa de Metal",
  "Base.SpearScissors": "Lança com Tesoura",
  "Base.SpearScrapKnife": "Lança com Faca de Sucata Metálica",
  "Base.SpearScrewdriver": "Lança com Chave de Fenda",
  "Base.SpearShort": "Lança com Ponta de Metal",
  "Base.SpearSteakKnife": "Lança com Faca de Churrasco",
  "Base.SpearStone": "Lança com Ponta de Pedra",
  "Base.SpearStoneLong": "Lança com Ponta Longa de Pedra",
  "Base.Spear_Bone": "Lança com Ponta de Osso",
  "Base.Spear_BoneLong": "Lança com Ponta Longa de Osso",
  "Base.Spear_Plunger": "Lança com Desentupidor",
  "Base.SpikedShortBat": "Bastão Curto com Espinhos",
  "Base.Spoon": "Colher",
  "Base.SpoonForged": "Colher Forjada",
  "Base.Spoon_Bone": "Colher de Osso",
  "Base.Spoon_Gold": "Colher de Ouro",
  "Base.Spoon_Silver": "Colher de Prata",
  "Base.Stake": "Estaca",
  "Base.SteakKnife": "Faca de Churrasco",
  "Base.SteelBar": "Barra de Aço",
  "Base.SteelBarHalf": "Meia Barra de Aço",
  "Base.SteelRodHalf": "Meia Haste de Aço",
  "Base.Stone2": "Pedra",
  "Base.StoneAxeLarge": "Machado Grande de Pedra",
  "Base.StoneKnifeLong": "Faca Longa de Pedra",
  "Base.StoneMaul": "Marreta de Pedra",
  "Base.SwitchKnife": "Canivete Automático",
  "Base.Sword": "Espada",
  "Base.Sword_Broken": "Espada Quebrada",
  "Base.Sword_Scrap": "Espada de Sucata Metálica",
  "Base.Sword_Scrap_Broken": "Espada de Sucata Metálica Quebrada",
  "Base.TableLeg": "Perna de Mesa Antiga",
  "Base.TableLeg_Broken": "Perna de Mesa Quebrada",
  "Base.TableLeg_Broken_Nails": "Perna de Mesa Quebrada com Pregos",
  "Base.TableLeg_Chain": "Perna de Mesa Antiga - Acorrentada",
  "Base.TableLeg_Nails": "Perna de Mesa Antiga com Pregos",
  "Base.TableLeg_Sawblade": "Perna de Mesa Antiga com Lâmina de Serra",
  "Base.TennisRacket": "Raquete de Tênis",
  "Base.TinOpener_Old": "Abridor de Latas - Modelo Antigo",
  "Base.TireIron": "Espátula para Desmontar Pneu",
  "Base.Toothbrush_Shiv": "Faca Improvisada de Escova de Dentes",
  "Base.TrapperCarbine": "Carabina de Caçador",
  "Base.TreeBranch2": "Galho",
  "Base.TreeBranch_Bone": "Galho com Espinhos de Osso",
  "Base.TreeBranch_Can": "Galho - Reforçado com Lata",
  "Base.TreeBranch_Nails": "Galho com Pregos",
  "Base.TreeBranch_Railspike": "Galho com Cravo Ferroviário",
  "Base.Trumpet": "Trompete",
  "Base.VarmintRifle": "Rifle MSR700",
  "Base.Violin": "Violino",
  "Base.WoodAxe": "Machado para Lenha",
  "Base.WoodAxeForged": "Machado para Lenha",
  "Base.WoodenMallet": "Macete de Madeira",
  "Base.WoodenStick2": "Haste de Madeira",
  "Base.WoodenStick_Broken": "Haste Quebrada",
  "Base.WoodenStick_Broken_Nails": "Haste Quebrada com Pregos",
  "Base.WoodenStick_Can": "Haste de Madeira - Reforçada com Lata",
  "Base.WoodenStick_Nails": "Haste de Madeira com Pregos",
  "Base.Wrench": "Chave Inglesa",
  "Base.YardstickDEBUG": "Régua de Debug"
};
